apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp3
  name: myapp3
  namespace: demo-app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp3
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
