apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp3
  name: myapp3
  namespace: demo-app3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp3
  type: LoadBalancer
status:
  loadBalancer: {}
