apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yourorganization/yourrepo.git
    path: myapp1
    targetRevision: HEAD
  destination:
    server: https://dev.cluster.server
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
